[package]
name = "fibonacci_rust"
version = "0.1.0"
authors = []

[lib]
name = "fibonacci_rust"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.20.0"
rustler_codegen = "0.20.0"
lazy_static = "1.0"
